version: '2'

services:
  tb-gateway:
    image: "thingsboard/gateway:1.2.1"
    environment:
      - GATEWAY_ACCESS_TOKEN=${GATEWAY_ACCESS_TOKEN}
      - GATEWAY_HOST=${GATEWAY_HOST}
    ports:
      - "9090:9090"
    entrypoint: /run-application.sh
